version: '3.8'
services:
  dev-database:
    image: postgres:15.0
    container_name: dev-database
    ports:
      - 5434:5432 #{port in host : port container}
    # inviroments variables
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 29102002
      POSTGRES_DB: furniture
    networks:
      - nestjs-network
networks:
  nestjs-network: